server:
  port: 端口
spring:
  application:
    name: reggie_01
  shardingsphere:
    datasource:
      names: master,slave
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://服务器IP:端口/库名?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
        username: ***
        password: ***
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://服务器IP:端口/库名?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
        username: ***
        password: ***
    masterslave:
      # 读写分离配置
      load-balance-algorithm-type: round_robin #轮询
      # 最终的数据源名称
      name: dataSource
      # 主库数据源名称
      master-data-source-name: master
      # 从库数据源名称列表，多个逗号分隔
      slave-data-source-names: slave
      props:
        sql:
          show: true #开启SQL显示，默认false
  redis:
    host: 服务器IP
    port: 服务器端口
    password: ***
    database: 0
  main:
    allow-bean-definition-overriding: true
cache:
  redis:
    time-to-live: 1800000 #设置缓存数据过期时间
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
reggie:
  path: /home/image/                   #D:\IDEA\JAVA Project\resource\